"""empty message

Revision ID: 056dd5c7288c
Revises: b627be59e220
Create Date: 2023-07-30 20:26:46.127243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056dd5c7288c'
down_revision = 'b627be59e220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_users_goals')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))

    with op.batch_alter_table('all_users_data', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('savings_percent',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('min_goal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('max_goal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('increase_decrease',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_users_data', schema=None) as batch_op:
        batch_op.alter_column('increase_decrease',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
        batch_op.alter_column('max_goal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('min_goal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('savings_percent',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
        batch_op.alter_column('month',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('username')

    op.create_table('all_users_goals',
    sa.Column('records', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('acc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goals', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('records', name='all_users_goals_pkey')
    )
    # ### end Alembic commands ###
