"""empty message

Revision ID: 2b73d11e762f
Revises: dd8bbcd35099
Create Date: 2023-07-30 14:01:39.880043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b73d11e762f'
down_revision = 'dd8bbcd35099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_monthly_data',
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('acc_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.DateTime(), nullable=True),
    sa.Column('beginning_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monthly_expense', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('wants_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('needs_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('savings_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_goal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_goal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('increase_decrease', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('records')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_monthly_data')
    # ### end Alembic commands ###
