"""empty message

Revision ID: 316dae1d85ef
Revises: 800b98e8c241
Create Date: 2023-07-24 01:49:48.644751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316dae1d85ef'
down_revision = '800b98e8c241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_user_data')
    with op.batch_alter_table('all_users_data', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('savings_percent',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('min_goal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('max_goal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('budget_increase',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.alter_column('acc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('user_goals_acc_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.create_foreign_key('user_goals_acc_id_fkey', 'account', ['acc_id'], ['id'])
        batch_op.alter_column('acc_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('all_users_data', schema=None) as batch_op:
        batch_op.alter_column('budget_increase',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
        batch_op.alter_column('max_goal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('min_goal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('savings_percent',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
        batch_op.alter_column('month',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    op.create_table('all_user_data',
    sa.Column('records', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('acc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('beginning_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('monthly_income', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('monthly_expense', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('current_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('wants_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('needs_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('savings_percent', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('budget_increase', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('min_goal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_goal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('records', name='uq_records_id')
    )
    # ### end Alembic commands ###
