"""empty message

Revision ID: 40d6b0def0a1
Revises: 424383bc5891
Create Date: 2023-07-22 20:42:17.225319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d6b0def0a1'
down_revision = '424383bc5891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('increasedecrease', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_report', schema=None) as batch_op:
        batch_op.drop_column('increasedecrease')

    # ### end Alembic commands ###
