"""empty message

Revision ID: 800b98e8c241
Revises: 6bdc915b3120
Create Date: 2023-07-23 17:01:08.978070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800b98e8c241'
down_revision = '6bdc915b3120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_goals',
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('acc_id', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['acc_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('records')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_goals')
    # ### end Alembic commands ###
