"""empty message

Revision ID: 825c93f4a562
Revises: 316dae1d85ef
Create Date: 2023-07-24 03:47:39.256213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825c93f4a562'
down_revision = '316dae1d85ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('increase_decrease', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('increasedecrease')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('increasedecrease', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('increase_decrease')

    # ### end Alembic commands ###
