"""empty message

Revision ID: d17fe75f5bec
Revises: c83ebda5928e
Create Date: 2023-07-27 22:03:43.471725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17fe75f5bec'
down_revision = 'c83ebda5928e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_goals',
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('acc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('goals', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('records')
    )
    op.drop_table('all_users_goals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_users_goals',
    sa.Column('records', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('acc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goals', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('records', name='user_goals_pkey')
    )
    op.drop_table('user_goals')
    # ### end Alembic commands ###
