"""empty message

Revision ID: dd8bbcd35099
Revises: d17fe75f5bec
Create Date: 2023-07-29 23:45:26.369954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8bbcd35099'
down_revision = 'd17fe75f5bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beginning_balance', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_report', schema=None) as batch_op:
        batch_op.drop_column('beginning_balance')

    # ### end Alembic commands ###
